/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto;

import java.awt.BasicStroke;
import java.awt.Color;
import javax.swing.JFrame;

import java.awt.Color;
import java.awt.BasicStroke;
import java.awt.Color;
 
import javax.swing.JFrame;
 
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.xy.XYLineAndShapeRenderer;
import org.jfree.data.xy.XYDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author anita
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    
    double auxNI;
    double auxNR;
    double auxNI2;
    double auxNR2;

    
    public Calculadora() {
        initComponents(); //Inicializamos componente
        setLocationRelativeTo(null); //Inicializamos pocicion donde aparecera
        
        //En los siguientes se inabilitan las casillas de resultados
        resultadoConjugado.setEnabled(false); 
        ResultadoMagnitud.setEnabled(false);
        resultadoEuler.setEnabled(false);
    }

    public double getAuxNI() {
        return auxNI;
    }

    public void setAuxNI(double auxNI) {
        this.auxNI = auxNI;
    }

    public double getAuxNR() {
        return auxNR;
    }

    public void setAuxNR(double auxNR) {
        this.auxNR = auxNR;
    }

    public double getAuxNI2() {
        return auxNI2;
    }

    public void setAuxNI2(double auxNI2) {
        this.auxNI2 = auxNI2;
    }

    public double getAuxNR2() {
        return auxNR2;
    }

    public void setAuxNR2(double auxNR2) {
        this.auxNR2 = auxNR2;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NumeroReal = new javax.swing.JTextField();
        NumeroComplejo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        BtnSuma = new javax.swing.JButton();
        BtnMulti = new javax.swing.JButton();
        BtnDivi = new javax.swing.JButton();
        BtnResta = new javax.swing.JButton();
        BtnBorrar = new javax.swing.JButton();
        BtnIgual = new javax.swing.JButton();
        BtnConjugado = new javax.swing.JButton();
        resultadoConjugado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Display = new javax.swing.JLabel();
        BtnTrigo = new javax.swing.JButton();
        BtnMagnitud = new javax.swing.JButton();
        ResultadoMagnitud = new javax.swing.JTextField();
        BtnGraficar = new javax.swing.JButton();
        DisplayTrigo = new javax.swing.JLabel();
        BtnEuler = new javax.swing.JButton();
        resultadoEuler = new javax.swing.JTextField();
        numRaiz = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        BtnRaiz = new javax.swing.JButton();
        listaRaices = new java.awt.List();
        BtnGraficaRaiz = new javax.swing.JButton();
        MagnitudTri = new javax.swing.JTextField();
        AnguloTri = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        BtnTrigonometrica = new javax.swing.JButton();
        BtnTrigo_A_Complejo = new javax.swing.JButton();
        BtnIngresarEuler = new javax.swing.JButton();
        Potencia = new javax.swing.JTextField();
        BtnDeMoivre = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora de Numeros Complejos");
        setAutoRequestFocus(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NumeroReal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        NumeroReal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        NumeroReal.setText("0");
        NumeroReal.setAutoscrolls(false);
        NumeroReal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeroRealActionPerformed(evt);
            }
        });
        getContentPane().add(NumeroReal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 150, 39));

        NumeroComplejo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        NumeroComplejo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        NumeroComplejo.setText("0");
        NumeroComplejo.setAutoscrolls(false);
        NumeroComplejo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeroComplejoActionPerformed(evt);
            }
        });
        getContentPane().add(NumeroComplejo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 150, 39));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("i");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, -1, -1));

        BtnSuma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/imagenes/Suma.png"))); // NOI18N
        BtnSuma.setBorderPainted(false);
        BtnSuma.setContentAreaFilled(false);
        BtnSuma.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/imagenes/suma_presionado.png"))); // NOI18N
        BtnSuma.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/imagenes/suma_mouse.png"))); // NOI18N
        BtnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSumaActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 151, 54, 54));

        BtnMulti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/imagenes/X.png"))); // NOI18N
        BtnMulti.setBorderPainted(false);
        BtnMulti.setContentAreaFilled(false);
        BtnMulti.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/imagenes/X_presionado.png"))); // NOI18N
        BtnMulti.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/imagenes/X_mouse.png"))); // NOI18N
        BtnMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMultiActionPerformed(evt);
            }
        });
        getContentPane().add(BtnMulti, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 233, 54, 54));

        BtnDivi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/imagenes/Division.png"))); // NOI18N
        BtnDivi.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/imagenes/Division_presionado.png"))); // NOI18N
        BtnDivi.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/imagenes/Division_mouse.png"))); // NOI18N
        BtnDivi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDiviActionPerformed(evt);
            }
        });
        getContentPane().add(BtnDivi, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 151, 54, 54));

        BtnResta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/imagenes/Resta.png"))); // NOI18N
        BtnResta.setBorderPainted(false);
        BtnResta.setContentAreaFilled(false);
        BtnResta.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/imagenes/Resta_presionado.png"))); // NOI18N
        BtnResta.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/imagenes/Resta_mouse.png"))); // NOI18N
        BtnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRestaActionPerformed(evt);
            }
        });
        getContentPane().add(BtnResta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 54, 54));

        BtnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/imagenes/AC.png"))); // NOI18N
        BtnBorrar.setBorderPainted(false);
        BtnBorrar.setContentAreaFilled(false);
        BtnBorrar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/imagenes/AC_presionado.png"))); // NOI18N
        BtnBorrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/imagenes/AC_mouse.png"))); // NOI18N
        getContentPane().add(BtnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 233, 54, 54));

        BtnIgual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/imagenes/Igual.png"))); // NOI18N
        BtnIgual.setBorderPainted(false);
        BtnIgual.setContentAreaFilled(false);
        BtnIgual.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/imagenes/Igual_presionado.png"))); // NOI18N
        BtnIgual.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/imagenes/Igual_mouse.png"))); // NOI18N
        BtnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIgualActionPerformed(evt);
            }
        });
        getContentPane().add(BtnIgual, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 54, 54));

        BtnConjugado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/imagenes/complemento.png"))); // NOI18N
        BtnConjugado.setBorderPainted(false);
        BtnConjugado.setContentAreaFilled(false);
        BtnConjugado.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/imagenes/complemento_presionado.png"))); // NOI18N
        BtnConjugado.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/imagenes/complemento_mouse.png"))); // NOI18N
        getContentPane().add(BtnConjugado, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 314, 54, 54));

        resultadoConjugado.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        resultadoConjugado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        resultadoConjugado.setText("Nulo");
        resultadoConjugado.setDisabledTextColor(new java.awt.Color(0, 102, 255));
        resultadoConjugado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoConjugadoActionPerformed(evt);
            }
        });
        getContentPane().add(resultadoConjugado, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 314, 159, 50));

        jLabel2.setText("Numero Real");
        jLabel2.setAutoscrolls(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        jLabel3.setText("Numero Imaginario");
        jLabel3.setAutoscrolls(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, -1));

        Display.setBackground(new java.awt.Color(0, 255, 255));
        Display.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        Display.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Display.setText("0+0i");
        getContentPane().add(Display, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 11, 414, 69));

        BtnTrigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/imagenes/TRIGON.png"))); // NOI18N
        BtnTrigo.setBorderPainted(false);
        BtnTrigo.setContentAreaFilled(false);
        BtnTrigo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/imagenes/TRIGON_presionado.png"))); // NOI18N
        BtnTrigo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/imagenes/TRIGON_MOUSE.png"))); // NOI18N
        BtnTrigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTrigoActionPerformed(evt);
            }
        });
        getContentPane().add(BtnTrigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 314, 54, 54));

        BtnMagnitud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/imagenes/modulo.png"))); // NOI18N
        BtnMagnitud.setBorderPainted(false);
        BtnMagnitud.setContentAreaFilled(false);
        BtnMagnitud.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/imagenes/modulo_presionado.png"))); // NOI18N
        BtnMagnitud.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/imagenes/modulo_mouse.png"))); // NOI18N
        getContentPane().add(BtnMagnitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 396, 54, 54));

        ResultadoMagnitud.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ResultadoMagnitud.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ResultadoMagnitud.setText("Nulo");
        ResultadoMagnitud.setDisabledTextColor(new java.awt.Color(0, 102, 255));
        getContentPane().add(ResultadoMagnitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 159, 54));

        BtnGraficar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/imagenes/grafica1.png"))); // NOI18N
        BtnGraficar.setBorderPainted(false);
        BtnGraficar.setContentAreaFilled(false);
        BtnGraficar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/imagenes/grafica1_presionado.png"))); // NOI18N
        BtnGraficar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/imagenes/grafica1_mouse.png"))); // NOI18N
        BtnGraficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGraficarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnGraficar, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 396, 54, 54));

        DisplayTrigo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DisplayTrigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DisplayTrigo.setText("r(cos + i sen)");
        getContentPane().add(DisplayTrigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 328, 39));

        BtnEuler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/imagenes/euler.png"))); // NOI18N
        BtnEuler.setBorderPainted(false);
        BtnEuler.setContentAreaFilled(false);
        BtnEuler.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/imagenes/EULER2_presionado.png"))); // NOI18N
        BtnEuler.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/imagenes/euler_mouse.png"))); // NOI18N
        BtnEuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEulerActionPerformed(evt);
            }
        });
        getContentPane().add(BtnEuler, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 54, 54));

        resultadoEuler.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        resultadoEuler.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        resultadoEuler.setText("ie^(iø)");
        resultadoEuler.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        resultadoEuler.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        resultadoEuler.setSelectionColor(new java.awt.Color(0, 0, 0));
        resultadoEuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoEulerActionPerformed(evt);
            }
        });
        getContentPane().add(resultadoEuler, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 153, 50));

        numRaiz.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numRaiz.setText("0");
        getContentPane().add(numRaiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, 59, 21));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Raiz");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 40, 21));

        BtnRaiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/imagenes/raices.png"))); // NOI18N
        BtnRaiz.setBorderPainted(false);
        BtnRaiz.setContentAreaFilled(false);
        BtnRaiz.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/imagenes/raices_presionado.png"))); // NOI18N
        BtnRaiz.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/imagenes/raices_mouse.png"))); // NOI18N
        getContentPane().add(BtnRaiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 54, 54));

        listaRaices.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        listaRaices.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        getContentPane().add(listaRaices, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, 153, 120));

        BtnGraficaRaiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/imagenes/gr.png"))); // NOI18N
        BtnGraficaRaiz.setBorderPainted(false);
        BtnGraficaRaiz.setContentAreaFilled(false);
        BtnGraficaRaiz.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/imagenes/gr_presionado.png"))); // NOI18N
        BtnGraficaRaiz.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/imagenes/gr_mouse.png"))); // NOI18N
        BtnGraficaRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGraficaRaizActionPerformed(evt);
            }
        });
        getContentPane().add(BtnGraficaRaiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, 54, 54));

        MagnitudTri.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        MagnitudTri.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        MagnitudTri.setText("0");
        MagnitudTri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MagnitudTriActionPerformed(evt);
            }
        });
        getContentPane().add(MagnitudTri, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 82, -1));

        AnguloTri.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        AnguloTri.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        AnguloTri.setText("0");
        AnguloTri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnguloTriActionPerformed(evt);
            }
        });
        getContentPane().add(AnguloTri, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, 82, -1));

        jLabel6.setText("Magnitud");
        jLabel6.setAutoscrolls(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, -1, 23));

        jLabel7.setText("Angulo");
        jLabel7.setAutoscrolls(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(761, 81, -1, 23));

        BtnTrigonometrica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/imagenes/TRIGON.png"))); // NOI18N
        BtnTrigonometrica.setBorderPainted(false);
        BtnTrigonometrica.setContentAreaFilled(false);
        BtnTrigonometrica.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/imagenes/TRIGON_presionado.png"))); // NOI18N
        BtnTrigonometrica.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/imagenes/TRIGON_MOUSE.png"))); // NOI18N
        BtnTrigonometrica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTrigonometricaActionPerformed(evt);
            }
        });
        getContentPane().add(BtnTrigonometrica, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 54, 54));

        BtnTrigo_A_Complejo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/imagenes/COMPLEJO.png"))); // NOI18N
        BtnTrigo_A_Complejo.setBorderPainted(false);
        BtnTrigo_A_Complejo.setContentAreaFilled(false);
        BtnTrigo_A_Complejo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/imagenes/COMPLEJO_presionado.png"))); // NOI18N
        BtnTrigo_A_Complejo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/imagenes/COMPLEJO_MOUSE.png"))); // NOI18N
        BtnTrigo_A_Complejo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTrigo_A_ComplejoActionPerformed(evt);
            }
        });
        getContentPane().add(BtnTrigo_A_Complejo, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 110, 54, 54));

        BtnIngresarEuler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/imagenes/EULER2.png"))); // NOI18N
        BtnIngresarEuler.setBorderPainted(false);
        BtnIngresarEuler.setContentAreaFilled(false);
        BtnIngresarEuler.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/imagenes/EULER2_presionado.png"))); // NOI18N
        BtnIngresarEuler.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/imagenes/EULER2_mouse.png"))); // NOI18N
        BtnIngresarEuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIngresarEulerActionPerformed(evt);
            }
        });
        getContentPane().add(BtnIngresarEuler, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, 54, 54));

        Potencia.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Potencia.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Potencia.setText("0");
        Potencia.setAutoscrolls(false);
        Potencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PotenciaActionPerformed(evt);
            }
        });
        getContentPane().add(Potencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 38, 39));

        BtnDeMoivre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/imagenes/MOIVRE.png"))); // NOI18N
        BtnDeMoivre.setBorderPainted(false);
        BtnDeMoivre.setContentAreaFilled(false);
        BtnDeMoivre.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/imagenes/MOIVRE_presionado.png"))); // NOI18N
        BtnDeMoivre.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/imagenes/MOIVRE_mouse.png"))); // NOI18N
        BtnDeMoivre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeMoivreActionPerformed(evt);
            }
        });
        getContentPane().add(BtnDeMoivre, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 54, 54));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMultiActionPerformed
         auxNI2=(Double.parseDouble(NumeroComplejo.getText()));
        auxNR2=(Double.parseDouble(NumeroReal.getText()));
    }//GEN-LAST:event_BtnMultiActionPerformed

    private void BtnDiviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDiviActionPerformed
          auxNI2=(Double.parseDouble(NumeroComplejo.getText()));
        auxNR2=(Double.parseDouble(NumeroReal.getText()));
    }//GEN-LAST:event_BtnDiviActionPerformed

    private void NumeroComplejoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeroComplejoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumeroComplejoActionPerformed

    private void NumeroRealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeroRealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumeroRealActionPerformed

    private void BtnTrigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTrigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnTrigoActionPerformed

    private void BtnGraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGraficarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnGraficarActionPerformed

    private void BtnEulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEulerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnEulerActionPerformed

    private void resultadoEulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoEulerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultadoEulerActionPerformed

    private void resultadoConjugadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoConjugadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultadoConjugadoActionPerformed

    private void BtnGraficaRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGraficaRaizActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnGraficaRaizActionPerformed

    private void BtnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSumaActionPerformed
         auxNI2=(Double.parseDouble(NumeroComplejo.getText()));
        auxNR2=(Double.parseDouble(NumeroReal.getText()));
        System.out.println("NR2:"+auxNR2);
        System.out.println("NI2:"+auxNI2);
    }//GEN-LAST:event_BtnSumaActionPerformed

    private void MagnitudTriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MagnitudTriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MagnitudTriActionPerformed

    private void AnguloTriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnguloTriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AnguloTriActionPerformed

    private void BtnTrigonometricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTrigonometricaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnTrigonometricaActionPerformed

    private void BtnTrigo_A_ComplejoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTrigo_A_ComplejoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnTrigo_A_ComplejoActionPerformed

    private void BtnIngresarEulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIngresarEulerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnIngresarEulerActionPerformed

    private void PotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PotenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PotenciaActionPerformed

    private void BtnDeMoivreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeMoivreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnDeMoivreActionPerformed

    private void BtnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIgualActionPerformed
       
    }//GEN-LAST:event_BtnIgualActionPerformed

    private void BtnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRestaActionPerformed
        auxNI2=(Double.parseDouble(NumeroComplejo.getText()));
        auxNR2=(Double.parseDouble(NumeroReal.getText()));
    }//GEN-LAST:event_BtnRestaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField AnguloTri;
    public javax.swing.JButton BtnBorrar;
    public javax.swing.JButton BtnConjugado;
    public javax.swing.JButton BtnDeMoivre;
    public javax.swing.JButton BtnDivi;
    public javax.swing.JButton BtnEuler;
    public javax.swing.JButton BtnGraficaRaiz;
    public javax.swing.JButton BtnGraficar;
    public javax.swing.JButton BtnIgual;
    public javax.swing.JButton BtnIngresarEuler;
    public javax.swing.JButton BtnMagnitud;
    public javax.swing.JButton BtnMulti;
    public javax.swing.JButton BtnRaiz;
    public javax.swing.JButton BtnResta;
    public javax.swing.JButton BtnSuma;
    public javax.swing.JButton BtnTrigo;
    public javax.swing.JButton BtnTrigo_A_Complejo;
    public javax.swing.JButton BtnTrigonometrica;
    public javax.swing.JLabel Display;
    public javax.swing.JLabel DisplayTrigo;
    public javax.swing.JTextField MagnitudTri;
    public javax.swing.JTextField NumeroComplejo;
    public javax.swing.JTextField NumeroReal;
    public javax.swing.JTextField Potencia;
    public javax.swing.JTextField ResultadoMagnitud;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    public java.awt.List listaRaices;
    public javax.swing.JTextField numRaiz;
    public javax.swing.JTextField resultadoConjugado;
    public javax.swing.JTextField resultadoEuler;
    // End of variables declaration//GEN-END:variables
}
